### ISSUE TITLE
Improve transaction query result

### ISSUE THREAD

**Issue by mingwho** [namshi/node-mysql#19]
```
let conn = await db.startTransaction(5)
let result = await conn.query(`SELECT 1`)
console.log(result)

// prints
[ [ { '1': 1 } ],
[ {
schema: '',
name: '1',
orgName: '',
table: '',
orgTable: '',
... blah blah ] ]
```

This can be confusing. The developer would expect query to return an array of objects,
but it returns a 2D array instead. Maybe we can get rid of the meta data in response.

**Comment by odino** [comment]
I think the connection object comes straight from the underlying MySQL library -- we could wrap it and "sanitize" the response:

https://github.com/sidorares/node-mysql2#using-promise-wrapper

``` js
// get the client
const mysql = require('mysql2');
// create the connection
const con = mysql.createConnection(
  {host:'localhost', user: 'root', database: 'test'}
);
con.promise().query("SELECT 1")
  .then( ([rows,fields]) => {
    console.log(rows);
  })
  .catch(console.log)
  .then( () => con.end());
```

The actual inconsistency, in our library, is that when we call a raw `.query(...)` we only return the first result: https://github.com/namshi/node-mysql/blob/master/index.js#L43

I'm in favor of actually making this a bit more pragmatic, but we'll need to break BC. For those who still want to access the metadata, we can also expose `conn.query_with_metadata(...)` so that there's an explicit method to receive metadata from a query.

**Comment by mingwho** [comment]
Thanks for the comment! Definitely helpful :) 
Yes I think we can add in the `conn.query_with_metadata(...)` so it stays consistent and people can also access the metadata if they need it

**Comment by mingwho** [comment]
As of now, we don't really have a use case for query with metadata so closing this :)
